<a href="https://colab.research.google.com/github/kirath2205/Information-Retrieval/blob/main/BMW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
bmw = pd.read_csv('BMW_Verified.csv')
bmw.drop("Unnamed: 0",axis=1, inplace=True)
bmw = bmw[(bmw['Label']==1) | (bmw['Label']==0) | (bmw['Label']==-1)]
bmw.reset_index(inplace=True, drop=True)
bmw.head()

id        username    created_at             date  Label  \
0  1.510000e+18       23ABCNews  1.650000e+12  29/3/2022 23:45   -1.0   
1  1.510000e+18  CloseHouseGolf  1.650000e+12  29/3/2022 23:30    1.0   
2  1.510000e+18      GadgetFlow  1.650000e+12  29/3/2022 23:30    1.0   
3  1.510000e+18   TheBoltonNews  1.650000e+12  29/3/2022 23:02   -1.0   
4  1.510000e+18          BMW_UK  1.650000e+12  29/3/2022 22:33   -1.0   

                                               tweet language  \
0  UPDATE: CHP said a man was killed Monday night...       en   
1  Another incredible Close House VIP car deliver...       en   
2  The @BMW Motorrad Definition CE 04 sit-on #eSc...       en   
3  'A tragedy for all concerned': Speeding driver...       en   
4  @lynpaul6 Hi Lyn, we're sorry to hear your BMW...       en   

                         hashtags cashtags  \
0                              []       []   
1      ['bmw', 'vip', 'dreamcar']       []   
2  ['escooter', 'transportation']       []   
3                              []       []   
4                              []       []   

                                                link  \
0  https://twitter.com/23ABCNews/status/150883271...   
1  https://twitter.com/CloseHouseGolf/status/1508...   
2  https://twitter.com/GadgetFlow/status/15088288...   
3  https://twitter.com/TheBoltonNews/status/15088...   
4  https://twitter.com/BMW_UK/status/150881450842...   

                                                urls  \
0  ['https://www.turnto23.com/news/local-news/one...   
1                                                 []   
2  ['https://thegadgetflow.com/portfolio/bmw-moto...   
3  ['https://www.theboltonnews.co.uk/news/2002930...   
4                                                 []   

                                              photos  video  \
0                                                 []      0   
1  ['https://pbs.twimg.com/media/FPBv1x2WQA49E4s....      1   
2  ['https://pbs.twimg.com/media/FPBv1chX0AcuHfs....      1   
3                                                 []      0   
4                                                 []      0   

                                         thumbnail  nlikes  nreplies  \
0                                              NaN       0         0   
1  https://pbs.twimg.com/media/FPBv1x2WQA49E4s.jpg       7         0   
2  https://pbs.twimg.com/media/FPBv1chX0AcuHfs.jpg       0         0   
3                                              NaN       1         0   
4                                              NaN       0         2   

   nretweets  
0          0  
1          0  
2          0  
3          1  
4          0

In [2]:
bmw.shape

(170, 17)

In [4]:
print(len(bmw[bmw['Label']==1]))
print(len(bmw[bmw['Label']==0]))
print(len(bmw[bmw['Label']==-1]))

80
34
56


In [ ]:
#Removing urls and stripping whitespaces
import re
for i in range(len(bmw['tweet'])):
    bmw['tweet'][i] = re.sub(r'http\S+', '', bmw['tweet'][i])
    bmw['tweet'][i] = bmw['tweet'][i].strip()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [ ]:
#Removing hashtags and mentions
for i in range(len(bmw['tweet'])):
    bmw['tweet'][i] = ' '.join([word for word in bmw['tweet'][i].split() if word[0]!='@' and word[0]!='#'])
    

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
#Lowercase all texts, remove stopwords, and lemmatize the texts
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# nltk.download('stopwords')
# nltk.download('wordnet')
 
stopwordsList = stopwords.words('english') 
lemmatizer = WordNetLemmatizer()


for i in range(len(bmw['tweet'])):
    bmw['tweet'][i] = bmw['tweet'][i].lower()
    bmw['tweet'][i] = ' '.join([word for word in bmw['tweet'][i].split() if word not in stopwordsList])
    bmw['tweet'][i] = ' '.join([lemmatizer.lemmatize(word) for word in bmw['tweet'][i].split()])

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()


In [ ]:
import numpy as np

X = np.array(bmw['tweet'].values.tolist())
y = np.array(bmw['Label'].astype(int).values.tolist())

from sklearn.model_selection import train_test_split
X_train, X_test , y_train, y_test = train_test_split(X, y , test_size = 0.10)

In [ ]:
from keras.preprocessing.text import Tokenizer
vocab_size = 50000
oov_token = "<OOV>"
tokenizer = Tokenizer(num_words = vocab_size, oov_token=oov_token)
tokenizer.fit_on_texts(X_train)

In [ ]:
word_index = tokenizer.word_index

In [ ]:
print(word_index)

{'<OOV>': 1, 'bmw': 2, 'car': 3, 'team': 4, 'driver': 5, 'driving': 6, 'price': 7, 'new': 8, 'electric': 9, 'hi': 10, 'vehicle': 11, 'get': 12, 'first': 13, 'year': 14, 'model': 15, '2': 16, 'customer': 17, 'possible': 18, 'soon': 19, '2022': 20, 'review': 21, 'range': 22, 'm4': 23, 'order': 24, 'design': 25, '3': 26, '1': 27, 'ix': 28, '🔥': 29, 'impact': 30, 'touch': 31, 'speeding': 32, 'old': 33, 'influence': 34, 'crashed': 35, 'six': 36, 'inside': 37, 'teen': 38, 'injuries': 39, 'in': 40, 'performance': 41, 'cars': 42, 'dm': 43, 'contact': 44, 'number': 45, 'behind': 46, 'form': 47, 'i4': 48, 'drive': 49, 'road': 50, 'india': 51, 'm3': 52, 'following': 53, 'u': 54, 'series': 55, 'using': 56, 'vin': 57, 'amp': 58, 'april': 59, 'm2': 60, 'look': 61, 'bs': 62, 'competition': 63, 'costs': 64, 'geopolitical': 65, 'exchange': 66, 'read': 67, 'social': 68, 'medium': 69, 'call': 70, 'deputy': 71, 'said': 72, '17': 73, 'suv': 74, 'killing': 75, 'people': 76, 'reportedly': 77, 'suffered': 78,

In [ ]:
X_train_sequences = tokenizer.texts_to_sequences(X_train)

In [ ]:
X_test_sequences = tokenizer.texts_to_sequences(X_test)

In [ ]:
max_length = 100
padding_type='post'
truncation_type='post'

from keras.preprocessing.sequence import pad_sequences

X_test_padded = pad_sequences(X_test_sequences,maxlen=max_length, padding=padding_type, truncating=truncation_type)
X_train_padded = pad_sequences(X_train_sequences,maxlen=max_length, padding=padding_type, truncating=truncation_type)


In [ ]:
!wget --no-check-certificate \
     http://nlp.stanford.edu/data/glove.6B.zip \
     -O /tmp/glove.6B.zip

--2022-04-02 03:59:07--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2022-04-02 03:59:07--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2022-04-02 03:59:07--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘/tmp/glove.6B.zip’

/t

In [ ]:
import os
import zipfile
with zipfile.ZipFile('/tmp/glove.6B.zip', 'r') as zip_ref:
    zip_ref.extractall('/tmp/glove')

In [ ]:
import numpy as np
embeddings_index = {}
f = open('/tmp/glove/glove.6B.100d.txt')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' % len(embeddings_index))

Found 400000 word vectors.


In [ ]:
embedding_matrix = np.zeros((len(word_index) + 1, max_length))
for word, i in word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # words not found in embedding index will be all-zeros.
        embedding_matrix[i] = embedding_vector

In [ ]:
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional

embedding_layer = Embedding(input_dim=len(word_index) + 1,
                            output_dim=max_length,
                            weights=[embedding_matrix],
                            input_length=max_length,
                            trainable=False)

In [ ]:
from tensorflow.keras.models import Sequential
model = Sequential([
    embedding_layer,
    Bidirectional(LSTM(150, return_sequences=True)), 
    Bidirectional(LSTM(150)),
    Dense(128, activation='relu'),
   Dense(3, activation='softmax')
])

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
training_padded = np.array(X_train_padded, dtype=np.uint8)
training_labels = np.array(y_train, dtype=np.uint8)
testing_padded = np.array(X_test_padded, dtype=np.uint8)
testing_labels = np.array(y_test, dtype=np.uint8)

In [ ]:
import tensorflow
y_train = tensorflow.keras.utils.to_categorical(y_train, 3)
y_test = tensorflow.keras.utils.to_categorical(y_test, 3)

from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
%load_ext tensorboard
!rm -rf logs

log_folder = 'logs'
callbacks = [
            EarlyStopping(patience = 10),
            TensorBoard(log_dir=log_folder)
            ]
num_epochs = 2
history = model.fit(X_train_padded, y_train, epochs=num_epochs, validation_data=(X_test_padded, y_test),callbacks=callbacks)

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
Epoch 1/2


ValueError: ignored

In [ ]:
# from keras.preprocessing.text import Tokenizer
# from keras.preprocessing.sequence import pad_sequences
# from keras import regularizers

# max_words = 5000
# max_len = 200

# tokenizer = Tokenizer(num_words=max_words)
# tokenizer.fit_on_texts(data)
# sequences = tokenizer.texts_to_sequences(data)
# tweets = pad_sequences(sequences, maxlen=max_len)
# print(tweets)

[[  0   0   0 ...   1 233 113]
 [  0   0   0 ... 236  65  66]
 [  0   0   0 ... 243 244 245]
 ...
 [  0   0   0 ... 110 111  56]
 [  0   0   0 ... 119 802 180]
 [  0   0   0 ... 229 805  87]]
